config/routes.rb
Rails.application.routes.draw do
  resources   :production_items
  resources   :production_formulas
  devise_for  :users
  resources   :production_schedules
  resources   :weeks_supply_calcs
  root 'production_schedules#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/production_item.rb
class ProductionItem < ActiveRecord::Base
  belongs_to :created_by, class_name: 'User', foreign_key: :creator_id
  belongs_to :updated_by, class_name: 'User', foreign_key: :updater_id
  belongs_to :production_formula
  belongs_to :item_master
  has_one    :master_formula, through: :item_master

  validates :item_master_id, :production_formula_id, presence: true
  validates :item_master_id, uniqueness: { scope: :production_formula_id }
  validates :quantity, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def tons
    quantity * item_master.weight / 2000
  end

  def components
    quantity * item_master.weight / master_formula.formula_components.to_a.sum { |formula| formula.blend_percentage * \
                                                            (1 - formula.component_shrinkage.shrinkage) } / 2000
  end
end

app/controllers/production_items_controller.rb
class ProductionItemsController < ApplicationController
  before_filter :can_view
  before_action :has_param, only: [:index, :new]
  helper_method :entry, :item, :formula
  respond_to :html

  def index
    @production_items = ProductionItem.where(production_formula_id: params[:production_formula_id])
  end

  def create
    render :new and return unless entry.valid?

    handle_service_result(item_create,
                    -> { redirect_to production_items_url(production_formula_id: params[:entry][:production_formula_id]) },
                    -> { render :new })
  end

  def update
    render :edit and return unless entry.valid?

    handle_service_result(item_update,
                    -> { redirect_to production_items_url(production_formula_id: item.production_formula_id) },
                    -> { render :edit })
  end

  def destroy
    item_delete
    respond_to do |format|
      format.html { redirect_to production_items_url(production_formula_id: item.production_formula_id), \
                    notice: 'Production Item was successfully destroyed.' }
    end
  end

  private
    def entry
      return @entry ||= ProductionItem.new(item_params) \
        if %{create new}.include?(params[:action])
      @entry ||= find_item
    end

    def item_create
      NewItem.call(item_params)
    end

    def item_update
      UpdateItem.call(item_params.merge(id: item.id))
    end

    def item_delete
      DeleteItem.call(item.attributes)
    end

    def item_params
      return {} if params[:entry].nil?

      params
        .require(:entry)
        .permit(:item_master_id, :production_formula_id, :quantity)
    end

    def item
      @production_item ||= params[:id] ? find_item : build_item
    end

    def build_item
      ProductionItem.new(item_params)
    end

    def find_item
      ProductionItem.find(params[:id])
    end

    def has_param
      if params[:production_formula_id]
        @production_formula = ProductionFormula.find(params[:production_formula_id])
      else
        redirect_to root_path()
      end
    end

    def formula
      @production_formula ||= find_formula
    end

    def find_formula
      @production_formula ||= params[:production_formula_id] ? ProductionFormula.find(params[:production_formula_id]) : \
                                                               ProductionFormula.find(params[:entry][:production_formula_id])
    end
end

app/helpers/production_items_helper.rb
module ProductionItemsHelper
end

app/views/production_items/_form.html.erb
<%= simple_form_for(entry, as: :entry, method: params[:id] ? :patch : :post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :production_formula, as: :hidden, input_html: \
                      { value: params[:id] ? item.production_formula_id : formula.id } %>
    <%= f.association :item_master, collection: ItemMaster.where(master_formula_id: \
                      params[:id] ? item.master_formula.id : formula.master_formula_id) \
                      , label_method: :item_name, value_method: :id, prompt:  "Choose an Item"  %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/production_items/_production_item.html.erb
<tr>
  <td><%= production_item.item_master.item_name %></td>
  <td><%= number_with_precision(production_item.quantity, precision: 0, delimiter: ',') %></td>
  <td><%= number_with_precision(production_item.tons, precision: 1, delimiter: ',') %></td>
  <td><%= link_to 'Show', production_item %></td>
  <td><%= link_to 'Edit', edit_production_item_path(production_item) %></td>
  <td><%= link_to 'Destroy', production_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/production_items/edit.html.erb
<h1>Editing Production Item</h1>

<%= render 'form' %>

<%= link_to 'Show', item, class: 'actions' %> |
<%= link_to 'Back', production_items_path(production_formula_id: item.production_formula_id) %>

app/views/production_items/index.html.erb
<%= link_to 'Back to Production Formula', production_formulas_url(production_schedule_id: @production_formula.production_schedule_id), class: 'btn btn-info' %>
<h1>Production Items</h1>
<%= link_to 'New Production Item', new_production_item_path(production_formula_id: params[:production_formula_id]), class: 'btn btn-warning' %>
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Item Number</th>
      <th>Quantity</th>
      <th>Tons</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @production_items %>
    <tr>
      <th>Total</th>
      <th><%= number_with_precision(@production_items.sum(:quantity), precision: 0, delimiter: ',') %></th>
      <th><%= number_with_precision(@production_items.inject(0) { |sum, p| sum + p.tons } , precision: 1, delimiter: ',') %></th>
      <th colspan="3">&nbsp;</th>
    </tr>
  </tbody>
</table>

<br>

app/views/production_items/new.html.erb
<h1>New Production Item</h1>

<%= render 'form' %>

<%= link_to 'Back', production_items_path(production_formula_id: formula.id), class: 'actions' %>

app/views/production_items/show.html.erb
<table class="table table-striped table-bordered showTable">
  <tr>
    <th>Item Master:</th>
    <td><%= item.item_master.item_name %></td>
  </tr>
  <tr>
    <th>Quantity:</th>
    <td><%= number_with_precision(item.quantity, precision: 0, delimiter: ',') %></td>
  </tr>
  <tr>
    <th>Created By:</th>
    <td><%= item.created_by.email %></td>
  </tr>
  <tr>
    <th>Created At:</th>
    <td><%= item.created_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Updated By:</th>
    <td><%= item.updated_by.email %></td>
  </tr>
  <tr>
    <th>Updated At:</th>
    <td><%= item.updated_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Action:</th>
    <td>
      <%= link_to 'Edit', edit_production_item_path(item) %> |
      <%= link_to 'Back', production_items_path(production_formula_id: item.production_formula_id) %>
    </td>
  </tr>
</table>