config/routes.rb
Rails.application.routes.draw do
  resources   :production_items
  resources   :production_formulas
  devise_for  :users
  resources   :production_schedules
  resources   :weeks_supply_calcs
  root 'production_schedules#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/production_schedule.rb
class ProductionSchedule < ActiveRecord::Base
  belongs_to :created_by, class_name: 'User', foreign_key: :creator_id
  belongs_to :updated_by, class_name: 'User', foreign_key: :updater_id
  has_many :production_formulas, dependent: :destroy

  validates :production_date, uniqueness: true, presence: true

  def total_tons
    production_formulas.to_a.sum { |f| f.tonnage }
  end

  def date_format
    production_date.strftime('%m/%d/%Y')
  end

  scope :ordered, lambda { order("production_date ASC") }
end

app/controllers/production_schedules_controller.rb
class ProductionSchedulesController < ApplicationController
  before_action :set_production_schedule, only: [:show, :edit, :update, :destroy]
  before_filter :can_view

  def index
    @production_schedules = ProductionSchedule.all.ordered
  end

  def show
  end

  def new
    @production_schedule = ProductionSchedule.new
  end

  def edit
  end

  def create
    @production_schedule = ProductionSchedule.new(production_schedule_params)

    respond_to do |format|
      if @production_schedule.save
        format.html { redirect_to production_schedules_url, notice: 'Production Schedule was successfully created.' }
        format.json { render :index, status: :created, location: production_schedules_url }
      else
        format.html { render :new }
        format.json { render json: @production_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @production_schedule.update(production_schedule_params)
        format.html { redirect_to production_schedules_url, notice: 'Production Schedule was successfully updated.' }
        format.json { render :index, status: :ok, location: production_schedules_url }
      else
        format.html { render :edit }
        format.json { render json: @production_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @production_schedule.destroy
    respond_to do |format|
      format.html { redirect_to production_schedules_url, notice: 'Production Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_production_schedule
      @production_schedule = ProductionSchedule.find(params[:id])
    end

    def production_schedule_params
      params.require(:production_schedule).permit(:production_date)
    end
end

app/helpers/production_schedules_helper.rb
module ProductionSchedulesHelper
end

app/views/production_schedules/_form.html.erb
<%= simple_form_for(@production_schedule) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :production_date, label: 'Production Week', as: :date, start_year: (Date.today - 30).year, end_year: (Date.today + 60).year, order: [:month, :day, :year], selected: Date.today.beginning_of_week - 1 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/production_schedules/_production_schedule.html.erb
<tr>
  <td><%= production_schedule.production_date.strftime('%m/%d/%Y') %></td>
  <td><%= number_with_precision(production_schedule.total_tons, precision: 0, delimiter: ',') %></td>
  <% if production_schedule.production_formulas.count == 0 %>
    <td><%= link_to 'Add Formulas', new_production_formula_path(production_schedule_id: production_schedule.id) %></td>
  <% else %>
    <td><%= link_to 'Show Formulas', production_formulas_url(production_schedule_id: production_schedule.id) %></td>
  <% end %>
  <td><%= link_to 'Show', production_schedule %></td>
  <td><%= link_to 'Edit', edit_production_schedule_path(production_schedule) %></td>
  <td><%= link_to 'Destroy', production_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/production_schedules/edit.html.erb
<h1>Editing Production Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @production_schedule, class: 'actions' %> |
<%= link_to 'Back', production_schedules_path %>

app/views/production_schedules/index.html.erb
<h1>Production Schedules</h1>

<%= link_to 'New Production Schedule', new_production_schedule_path, class: 'btn btn-warning' %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Production Week</th>
      <th>Scheduled Tons</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @production_schedules %>
  </tbody>
</table>

app/views/production_schedules/new.html.erb
<h1>New Production Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', production_schedules_path, class: 'actions' %>

app/views/production_schedules/show.html.erb
<table class="table table-striped table-bordered showTable">
  <tr>
    <th>Production Week:</th>
    <td><%= @production_schedule.production_date.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Created By:</th>
    <td><%= @production_schedule.created_by.email %></td>
  </tr>
  <tr>
    <th>Created At:</th>
    <td><%= @production_schedule.created_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Updated By:</th>
    <td><%= @production_schedule.updated_by.email %></td>
  </tr>
  <tr>
    <th>Updated At:</th>
    <td><%= @production_schedule.updated_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Action:</th>
    <td>
      <%= link_to 'Edit', edit_production_schedule_path(@production_schedule) %> |
      <%= link_to 'Back', production_schedules_path %>
    </td>
  </tr>
</table>