config/routes.rb
Rails.application.routes.draw do
  resources   :production_items
  resources   :production_formulas
  devise_for  :users
  resources   :production_schedules
  resources   :weeks_supply_calcs
  root 'production_schedules#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/production_formula.rb
class ProductionFormula < ActiveRecord::Base
  belongs_to  :created_by, class_name: 'User', foreign_key: :creator_id
  belongs_to  :updated_by, class_name: 'User', foreign_key: :updater_id
  belongs_to  :master_formula
  belongs_to  :production_schedule
  has_many    :production_items, dependent: :destroy

  validates :master_formula_id, :production_schedule_id, presence: true
  validates :production_schedule_id, uniqueness: { scope: :master_formula_id }
  validates :tonnage, numericality: { greater_than_or_equal_to: 0, only_integer: true, allow_blank: true }

  def tons
    production_items.to_a.sum { |item| item.tons }
  end

  def components
    production_items.to_a.sum { |item| item.components }
  end
end

app/controllers/production_formulas_controller.rb
class ProductionFormulasController < ApplicationController
  before_action :set_production_formula, only: [:show, :edit, :update, :destroy]
  before_filter :can_view
  before_action :has_param, only: [:index, :new]

  def index
    @production_formulas = ProductionFormula.where(production_schedule_id: params[:production_schedule_id])
  end

  def show
  end

  def new
    @production_formula = ProductionFormula.new
  end

  def edit
  end

  def create
    @production_formula = ProductionFormula.new(production_formula_params)

    respond_to do |format|
      if @production_formula.save
        format.html { redirect_to production_formulas_url(production_schedule_id: @production_formula.production_schedule.id), notice: 'Production Formula was successfully created.' }
        format.json { render :index, status: :created, location: production_formulas_url(production_schedule_id: @production_formula.production_schedule.id) }
      else
        format.html { render :new }
        format.json { render json: @production_formula.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @production_formula.update(production_formula_params)
        format.html { redirect_to production_formulas_url(production_schedule_id: @production_formula.production_schedule.id), notice: 'Production Formula was successfully updated.' }
        format.json { render :index, status: :ok, location: production_formulas_url(production_schedule_id: @production_formula.production_schedule.id) }
      else
        format.html { render :edit }
        format.json { render json: @production_formula.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @production_formula.destroy
    respond_to do |format|
      format.html { redirect_to production_formulas_url(production_schedule_id: @production_formula.production_schedule.id), notice: 'Production Formula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_production_formula
      @production_formula = ProductionFormula.find(params[:id])
    end

    def production_formula_params
      params.require(:production_formula).permit(:master_formula_id, :production_schedule_id, :tonnage)
    end

    def has_param
      unless params[:production_schedule_id]
        redirect_to root_path()
      end
    end
end

app/helpers/production_formulas_helper.rb
module ProductionFormulasHelper
end

app/views/production_formulas/_form.html.erb
<%= simple_form_for(@production_formula) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :master_formula, collection: MasterFormula.ordered, label_method: :formula_name, value_method: :id, prompt:  "Choose a Formula" %>
    <%= f.association :production_schedule, collection: ProductionSchedule.ordered, label_method: :date_format, value_method: :id, selected: params[:production_schedule_id] %>
    <%= f.input :tonnage %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/production_formulas/_production_formula.html.erb
<tr>
  <td><%= production_formula.master_formula.formula_name %></td>
  <td><%= production_formula.production_schedule.date_format %></td>
  <td><%= number_with_precision(production_formula.tonnage, precision: 1, delimiter: ',') %></td>
  <% if production_formula.production_items.count == 0 %>
    <td><%= link_to 'Add Items', new_production_item_path(production_formula_id: production_formula.id) %></td>
  <% else %>
    <td><%= link_to 'Show Items', production_items_url(production_formula_id: production_formula.id) %></td>
  <% end %>
  <td><%= link_to 'Show', production_formula %></td>
  <td><%= link_to 'Edit', edit_production_formula_path(production_formula) %></td>
  <td><%= link_to 'Destroy', production_formula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/production_formulas/edit.html.erb
<h1>Editing Production Formula</h1>

<%= render 'form' %>

<%= link_to 'Show', @production_formula, class: 'actions' %> |
<%= link_to 'Back', production_formulas_path(production_schedule_id: @production_formula.production_schedule.id) %>

app/views/production_formulas/index.html.erb
<%= link_to 'Back to Production Schedule', production_schedules_url, class: 'btn btn-info' %>
<h1>Production Formulas</h1>
<%= link_to 'New Production Formula', new_production_formula_path(production_schedule_id: params[:production_schedule_id]), class: 'btn btn-warning' %>
<%= link_to 'Calculate Tonnage', new_weeks_supply_calc_path(production_schedule_id: params[:production_schedule_id]), class: 'btn btn-warning' %>
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Master Formula</th>
      <th>Production Schedule</th>
      <th>Tonnage</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @production_formulas %>
    <tr>
      <th>&nbsp;</th>
      <th>Total</th>
      <th><%= number_with_precision(@production_formulas.sum(:tonnage), precision: 1, delimiter: ',') %></th>
      <th colspan="4">&nbsp;</th>
    </tr>
  </tbody>
</table>

<br>

app/views/production_formulas/new.html.erb
<h1>New Production Formula</h1>

<%= render 'form' %>

<%= link_to 'Back', production_formulas_path(production_schedule_id: params[:production_schedule_id]), class: 'actions' %>

app/views/production_formulas/show.html.erb
<table class="table table-striped table-bordered showTable">
  <tr>
    <th>Master Formula:</th>
    <td><%= @production_formula.master_formula.formula_name %></td>
  </tr>
  <tr>
    <th>Production Schedule:</th>
    <td><%= @production_formula.production_schedule.date_format %></td>
  </tr>
  <tr>
    <th>Tonnage:</th>
    <td><%= number_with_precision(@production_formula.tonnage, precision: 0, delimiter: ',') %></td>
  </tr>
  <tr>
    <th>Created By:</th>
    <td><%= @production_formula.created_by.email %></td>
  </tr>
  <tr>
    <th>Created At:</th>
    <td><%= @production_formula.created_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Updated By:</th>
    <td><%= @production_formula.updated_by.email %></td>
  </tr>
  <tr>
    <th>Updated At:</th>
    <td><%= @production_formula.updated_at.strftime('%m/%d/%Y') %></td>
  </tr>
  <tr>
    <th>Action:</th>
    <td>
      <%= link_to 'Edit', edit_production_formula_path(@production_formula) %> |
      <%= link_to 'Back', production_formulas_url(production_schedule_id: @production_formula.production_schedule.id) %>
    </td>
  </tr>
</table>